### ISSUE TITLE
Check style = strange behavior.

### ISSUE THREAD

**Issue by Axxon** [norsys/rothenberg#9]
Hello, i tried to create my first commit on a rothenberg stacked project but the check-style-php returns is strange, example:
```php
namespace AppBundle\Entity;
...
    /**
     * @param string $releaseId //l.28
     */
    public function __construct(string $releaseId)
    {
        $this->releaseId = $releaseId;
    }
...
```
Here the check-style output:

```
...
  28 | ERROR | Missing parameter comment
...
```
I have some other returns how look like this. So, finally i can't commit.

And:

```
FILE: /src/src/AppBundle/Entity/Item.php
----------------------------------------------------------------------
FOUND 10 ERRORS AFFECTING 10 LINES
----------------------------------------------------------------------
```

Why /src/src ?

**Comment by cedvan** [comment]
hi @Axxon,

`src/src` : 
- first `src` is the project path in container php-cli
- second `src` is the folder `src` in your project

A comment php doc sample : 
```php
    /**
     * @param type variable comment
     */
```

Try : 
```php
    /**
     * @param string $releaseId my-super-comment
     */
```

**Comment by Axxon** [comment]
Thx @cedvan, ha ! That's a 'my-super-comment' required, so it's too much for me, i will disabled that's thing later.
